import type { JSONSchemaType } from "ajv";
import type { RecoveryBundle } from "./recovery-bundle.js";

export const recoveryBundleSchema: JSONSchemaType<RecoveryBundle> = {
  type: "object",
  required: [
    "schemaVersion",
    "kind",
    "manifestId",
    "revisionHash",
    "receiptHash",
    "title",
    "artist",
    "editionSize",
    "network",
    "issuerAddress",
    "operatorAddress",
    "tokenIds",
    "txHashes",
    "transferFee",
    "metadataUri",
    "licenseUri",
    "coverCid",
    "mediaCid",
    "licenseType",
    "licenseSummary",
    "benefit",
    "generatedAt",
    "recoveryVersion",
    "instructions",
  ],
  properties: {
    schemaVersion: { type: "string", const: "1.0.0" },
    kind: { type: "string", const: "recovery-bundle" },
    manifestId: { type: "string", pattern: "^[a-f0-9]{64}$" },
    revisionHash: { type: "string", pattern: "^[a-f0-9]{64}$" },
    receiptHash: { type: "string", pattern: "^[a-f0-9]{64}$" },
    title: { type: "string", minLength: 1 },
    artist: { type: "string", minLength: 1 },
    editionSize: { type: "integer", minimum: 1 },
    network: { type: "string", enum: ["testnet", "devnet", "mainnet"] },
    issuerAddress: {
      type: "string",
      pattern: "^r[1-9A-HJ-NP-Za-km-z]{24,34}$",
    },
    operatorAddress: {
      type: "string",
      pattern: "^r[1-9A-HJ-NP-Za-km-z]{24,34}$",
    },
    tokenIds: {
      type: "array",
      items: { type: "string", minLength: 1 },
      minItems: 1,
    },
    txHashes: {
      type: "array",
      items: { type: "string", minLength: 1 },
      minItems: 1,
    },
    transferFee: { type: "integer", minimum: 0 },
    metadataUri: { type: "string", minLength: 1 },
    licenseUri: { type: "string", minLength: 1 },
    coverCid: { type: "string", minLength: 1 },
    mediaCid: { type: "string", minLength: 1 },
    licenseType: { type: "string", minLength: 1 },
    licenseSummary: { type: "string", minLength: 1 },
    benefit: {
      type: "object",
      required: ["kind", "description", "contentPointer"],
      properties: {
        kind: { type: "string", minLength: 1 },
        description: { type: "string", minLength: 1 },
        contentPointer: { type: "string", minLength: 1 },
      },
      additionalProperties: false,
    },
    accessPolicyLabel: { type: "string", nullable: true },
    qualifyingTokenIds: {
      type: "array",
      items: { type: "string" },
      nullable: true,
    },
    generatedAt: { type: "string" },
    recoveryVersion: { type: "string", const: "1.0.0" },
    instructions: {
      type: "array",
      items: { type: "string" },
      minItems: 1,
    },
    bundleHash: { type: "string", pattern: "^[a-f0-9]{64}$", nullable: true },
  },
  additionalProperties: false,
};
